### ISSUE TITLE
django-filter macht Sachen kaputt

### ISSUE THREAD

**Issue by bixel** [WoIstBier/bier-django#5]
Mit einem git-bisect stellt sich 'raus, dass der commit 66d4e65 die test-commands kaputt macht. Wenn ich die `django_filters`-Sachen in `woistbier_rest/views.py` herausnehme funktioniert es wieder. Ich konnte aber nicht herausfinden, was genau diesen Fehler verursacht. Möglicherweise ist das ein Konflikt zwischen REST und dem django-filters?

**Comment by bixel** [comment]
Das ist hier übrigens der Fehler:

```
$ python manage.py test --settings=woistbier.local_test_settings
INFO:woistbier.settings:Reading Settings!
INFO:woistbier.local_test_settings:Read local_test_settings. Using database: {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': './local_db.sqlite'}}
Traceback (most recent call last):
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/debug_toolbar/settings.py", line 243, in patch_all
    patch_root_urlconf()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/debug_toolbar/settings.py", line 231, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 549, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 351, in app_dict
    self._populate()
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 284, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/bixel/repos/bier/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/bixel/repos/bier/woistbier/urls.py", line 28, in <module>
    url(r'^bier/', include('woistbier_rest.urls')),
  File "/Users/bixel/repos/bier/env/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/bixel/repos/bier/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/bixel/repos/bier/woistbier_rest/urls.py", line 5, in <module>
    from woistbier_rest import views
  File "/Users/bixel/repos/bier/woistbier_rest/views.py", line 113, in <module>
    class BeerListFilter(django_filters.rest_framework.FilterSet):
AttributeError: module 'django_filters' has no attribute 'rest_framework'
```
